# --------------------------------- #
#    Kanae's Configuration file     #
# --------------------------------- #
# This holds the configuration for Kanae. This file is not settable during runtime.
# If you wish to change the values, change and save, and restart your server

# Entries pertaining to Kanae are located here
app:

  # Host that the server will use.
  # Set to 0.0.0.0 if running in Docker
  host: 127.0.0.1

  # Port that the server binds to.
  # Defaults to 8000
  port: 8000