app:

  # Host that the server will use.
  # Set to 0.0.0.0 if running in Docker
  host: 127.0.0.1

  # Port that the server binds to.
  # Defaults to 8000
  port: 8000

  api_key: AIzaSyA3BHoysobaoGBHOmsNzwuy3hFWnOzfSWw